version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file:
      - backend/cookbook/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - backend/cookbook/.env
    restart: always
    volumes:
      - static:/static/
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/static/
    depends_on:
      - backend
